spring:
  application:
    name: ezenBulja
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true  # HiddenHttpMethodFilter 활성화
  datasource:
    url: jdbc:h2:tcp://localhost/~/dontdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.thymeleaf: DEBUG
    ezen.ezenbulja.controller.CommentController: INFO
